import htmlwriter
from cStringIO import StringIO

def test_htmlwriter():
    s = StringIO()
    w = htmlwriter.WikiWriter(s)
    w.push('body')
    w.push('body')
    w.push('a')
    w.pop()
    w.push('body')
    w.insertc('br')
    w.insert('title','title')
    w.pop()
    w.text('hoganona')
    w.text('hdkkaskdfn')
    w.text('hoganona3')
    w.a('hogehoge',href='http://&&Jlkjasdf.lkjalsdf==++||/lsls;&amp;',cls='tt',id='hogehoge',lalal='asdf')
    o = htmlwriter.OUListWriter(w)
    o.move(1)
    w.text('a')
    o.move(2)
    w.text('bbbb1')
    w.text('bbbb2')
    w.text('bbbb3')
    o.move(1)
    w.text('a')
    o.move(1)
    w.text('a')
    o.move(1)
    o.move(2)
    w.text('bbbb1')
    w.text('bbbb2')
    w.text('bbbb3')
    w.text('a')
    o.move(1)
    w.text('a')
    o.finish()
    w.pop()
    w.pop()
